[package]
name = "digado"
version = "0.1.0"
authors = ["anders martini <andersmartini2@gmail.com>", "sam wilson <sam.wilson@mirado.com>"]

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
#diesel = { version = "1.0.0", features = ["postgres"] }
